# [[hooks]]
# stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "if [ ! -e tailwind.css ]; then touch tailwind.css; fi"]

[[hooks]]
stage = "build"
command = "./tailwindcss-macos-arm64"
command_arguments = ["-mo", "tailwind.css"]
